#! /bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

####################################################
#
# Build the Derby release distributions. After a successful run,
# release/distribution will hold all of the signed artifacts except
# for the Eclipse ui plugin. You will have to ask an Eclipse user to build
# that artifact for you.
#
# This script assumes that you have changed directory to the root of
# your code tree, where its build.xml and java directory live.
#
####################################################

if [ ! -n "$DOCS_ROOT" ]; then
    echo Please set DOCS_ROOT to the top directory of your doc client, where its build.xml and src directory live.
    exit 1
fi

export docLib=$DOCS_ROOT/lib
export CLASSPATH=$docLib/fop.jar:$docLib/avalon-framework-cvs-20020806.jar:$docLib/batik.jar
export ANT_OPTS="-Xmx512m"


read -p "Enter your Apache subversion username >  " subversionUserName
read -p "Enter your Apache subversion password >  " subversionPassword
read -p "Enter your pgp passphrase >  " pgpPassphrase

###############################################################
#
echo Building release distributions...
#
###############################################################

ant "-Ddocs.root=$DOCS_ROOT" "-Dpgp.passphrase=$pgpPassphrase" "-Dsvn.username=$subversionUserName" "-Dsvn.password=$subversionPassword" -quiet release
