#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REVISION=$1

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

# We have one catalog per platform
if [ ! -e ${TESTLOGDIR} ]
then
  echo "${TESTLOGDIR} does not exist"
  exit
fi

# Get the list of testsuite we are running:
TESTLISTFILE="${DERBYDIR}/testing/testlist"
SUITES=`gawk '{ print $1 }' ${TESTLISTFILE} | grep -v "^#"`

# Get the set of platforms
cd ${TESTLOGDIR}
PLATFORMS=`ls`

for PLATFORM in ${PLATFORMS}
do
  echo ""
  echo ${PLATFORM}
  # Create one file per platform
  BASELINEFILE="${PLATFORM}/baseline.csv"
  echo "# ${REVISION}" > ${BASELINEFILE}

  for SUITE in ${SUITES}
  do
    # DEBUG 
echo "SUITE: ${SUITE}"
    if [ "${SUITE}" == "exit" ]
    then
      exit
    fi
    TIME=`grep "^${SUITE} " ${PLATFORM}/${REVISION}.csv | gawk '{ sub("\r$", ""); print }' | gawk '{ print $6 }'`
                                                        # removes DOS endofline
    SECONDS=`${TOOLDIR}/toSeconds ${TIME}`
    echo "${SUITE} ${TIME} ${SECONDS}" >> ${BASELINEFILE}
  done # SUITES

done # PLATFORMS
