#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "THIS IS SITE SPECIFIC! FIX!"
exit

export USER="derbytester"
export HOME="/home/${USER}"

JOB=mkDerbyTestIndex_all

echo "----------------------------------------------------" > ${HOME}/cron/${JOB}.log
echo "----------------------------------------------------" > ${HOME}/cron/${JOB}.err
/bin/date >> ${HOME}/cron/${JOB}.log
/bin/date >> ${HOME}/cron/${JOB}.err

. ${HOME}/.bashrc >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"


export DERBYDIR="${HOME}/Apache/Derby/trunk_JDK15"
echo "${DERBYDIR} ----------------------------------" >> ${HOME}/cron/${JOB}.log
. ${DERBYDIR}/env.sh >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
. ${TOOLDIR}/env
${TOOLDIR}/${JOB} details >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
${TOOLDIR}/${JOB}         >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err

export DERBYDIR="${HOME}/Apache/Derby/tinderbox_trunk_JDK15"
echo "${DERBYDIR} ----------------------------------" >> ${HOME}/cron/${JOB}.log
. ${DERBYDIR}/env.sh >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
. ${TOOLDIR}/env
${TOOLDIR}/${JOB} details >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
${TOOLDIR}/${JOB}         >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err

export DERBYDIR="${HOME}/Apache/Derby/10.1_JDK15"
echo "${DERBYDIR} ----------------------------------" >> ${HOME}/cron/${JOB}.log
. ${DERBYDIR}/env.sh >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
. ${TOOLDIR}/env
${TOOLDIR}/${JOB} details >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
${TOOLDIR}/${JOB}         >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err

export DERBYDIR="${HOME}/Apache/Derby/trunk_JDK16"
echo "${DERBYDIR} ----------------------------------" >> ${HOME}/cron/${JOB}.log
. ${DERBYDIR}/env.sh >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
. ${TOOLDIR}/env
${TOOLDIR}/${JOB} details >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
${TOOLDIR}/${JOB}         >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err

export DERBYDIR="${HOME}/Apache/Derby/tinderbox_10.1_JDK15"
echo "${DERBYDIR} ----------------------------------" >> ${HOME}/cron/${JOB}.log
. ${DERBYDIR}/env.sh >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
. ${TOOLDIR}/env
${TOOLDIR}/${JOB} details >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err
${TOOLDIR}/${JOB}         >> ${HOME}/cron/${JOB}.log 2>>${HOME}/cron/${JOB}.err


/bin/date >> ${HOME}/cron/${JOB}.log
/bin/date >> ${HOME}/cron/${JOB}.err
