#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "THIS IS SITE SPECIFIC! FIX!"
exit

export USER="derbytester"
export HOME="/home/${USER}"

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

/bin/echo "-------------------------------------------------" > ${HOME}/cron/MkAllPlotDataAndPlots.log
/bin/echo "-------------------------------------------------" > ${HOME}/cron/MkAllPlotDataAndPlots.err
/bin/echo -n "${HOST} " >> ${HOME}/cron/MkAllPlotDataAndPlots.log
/bin/date >> ${HOME}/cron/MkAllPlotDataAndPlots.log
/bin/date >> ${HOME}/cron/MkAllPlotDataAndPlots.err

. ${HOME}/.bashrc >> ${HOME}/cron/MkAllPlotDataAndPlots.log 2>>${HOME}/cron/MkAllPlotDataAndPlots.err

#----------
# Built with JDK 1.5
export DERBYDIR="${HOME}/Apache/Derby/trunk_JDK15"
cd ${DERBYDIR}
${TOOLDIR}/mkAllPlotDataAndPlots     >> ${HOME}/cron/MkAllPlotDataAndPlots.log 2>>${HOME}/cron/MkAllPlotDataAndPlots.err

#----------
# Built with JDK 1.5
export DERBYDIR="${HOME}/Apache/Derby/tinderbox_trunk_JDK15"
cd ${DERBYDIR}
${TOOLDIR}/mkAllPlotDataAndPlots     >> ${HOME}/cron/MkAllPlotDataAndPlots.log 2>>${HOME}/cron/MkAllPlotDataAndPlots.err

#----------
# Built with JDK 1.5
export DERBYDIR="${HOME}/Apache/Derby/10.1_JDK15"
cd ${DERBYDIR}
${TOOLDIR}/mkAllPlotDataAndPlots     >> ${HOME}/cron/MkAllPlotDataAndPlots.log 2>>${HOME}/cron/MkAllPlotDataAndPlots.err

#----------
# Built with JDK 1.6
export DERBYDIR="${HOME}/Apache/Derby/trunk_JDK16"
cd ${DERBYDIR}
${TOOLDIR}/mkAllPlotDataAndPlots     >> ${HOME}/cron/MkAllPlotDataAndPlots.log 2>>${HOME}/cron/MkAllPlotDataAndPlots.err


/bin/echo "-------------------------------------------------" >> ${HOME}/cron/MkAllPlotDataAndPlots.log
/bin/echo "-------------------------------------------------" >> ${HOME}/cron/MkAllPlotDataAndPlots.err
/bin/date >> ${HOME}/cron/MkAllPlotDataAndPlots.log
/bin/date >> ${HOME}/cron/MkAllPlotDataAndPlots.err
