#!/bin/bash
# NB Assuming all CPUs are identical....
SYSINF="sysinf$$"
systeminfo > ${SYSINF}
NUMBER=`grep "Processor" ${SYSINF} | gawk '{ print $2 }'`
MODEL=`grep "System Model:" ${SYSINF} | gawk '{ print $3" "$4 }'`
MODEL2=`grep 'Mhz' ${SYSINF} | gawk '{ print $2" "$3" "$4" "$5" "$6" "$7" "$8" "$9 }'`
FREQ=`grep 'Mhz' ${SYSINF} | gawk '{ print $10 }'`
CACHE=`grep "Virtual Memory: Max Size" ${SYSINF} | gawk '{ print $5" "$6 }'`

MEMTOTAL=`grep "Total Physical Memory:" ${SYSINF} | gawk '{ print $4 }'`
MEMFREE=`grep "Available Physical Memory" ${SYSINF} | gawk '{ print $4" "$5 }'`

echo "${NUMBER} X [${MODEL} ${MODEL2}]: ${FREQ} MHz, ${CACHE} cache. ${MEMTOTAL} Total Memory."
rm ${SYSINF}
