#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

VAR=$1
# Only accepts _last20

GNUPLOT=/usr/local/bin/gnuplot

# Get the list of testsuite we are running:
TESTLISTFILE="${DERBYDIR}/testing/testlist"
SUITES=`gawk '{ print $1 }' ${TESTLISTFILE} | grep -v "^#"`

# Get the set of platforms
cd ${DERBYDIR}/testing/Full/plot
PLATFORMS=`ls ${DERBYDIR}/testing/testlog/`
echo ${PLATFORMS}
for  PLATFORM in ${PLATFORMS}
do
  echo "${PLATFORM}"
  mkdir -p ${PLATFORM}
  cd ${PLATFORM}
  for SUITE in ${SUITES}
  do
    cp ${SUITE}${VAR}.data data.dat
    $GNUPLOT < ${TOOLDIR}/gnuplot/duration.gp
    mv plot.png ${SUITE}${VAR}.png
    chmod go+r  ${SUITE}${VAR}.png
  done
  cd ../
done
