#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NB Assuming all CPUs are identical....
NUMBER=`cat  /proc/cpuinfo | grep "model name" | wc -l | sed -e 's/  //g'`
MODEL=`cat  /proc/cpuinfo | grep "model name" | head -1 | gawk -F: '{ print $2 }'`
FREQ=`cat  /proc/cpuinfo | grep "cpu MHz" | head -1 | gawk -F: '{ print $2 }'`
CACHE=`cat  /proc/cpuinfo | grep "cache size" | head -1 | gawk -F: '{ print $2 }'`

MEMTOTAL=`cat /proc/meminfo | grep "MemTotal" | gawk -F: '{ print $2 }' | sed -e 's/  //g'`
MEMFREE=`cat /proc/meminfo | grep "MemFree" | gawk -F: '{ print $2 }' | sed -e 's/  //g'`

echo "${NUMBER} X ${MODEL}: ${FREQ} MHz, ${CACHE} cache. ${MEMTOTAL} Total Memory."
