#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

# Define DERBYDIR
. ./env.sh

INIT=$1

echo "***** ${DERBYDIR} *********"

if [ "${INIT}" == "INIT" ]
then

  # Build plot data
  # ONLY initially, i.e. after a change of baseline or addition or removal of platform...
  # NB: createBaselineFilesOnePlatform / createBaselineFiles must have been run to create
  # baseline files for all platforms to be shown.
  echo "-- mkGNUplot ----------------------------------------"
  time ${TOOLDIR}/mkGNUplot

else

  # Update plot data:
  echo "-- mkGNUplot.recent -----------------------------------"
  time ${TOOLDIR}/mkGNUplot.recent

fi

# Create plots per platform
echo "-- doplot ---------------------------------------------"
time ${TOOLDIR}/doplot

# Create summary plots over all platforms
echo "-- doplot_all -----------------------------------------"
time ${TOOLDIR}/doplot_all


# Extract data for last 20 builds ( ~1 month)
echo "-- mkGNUplot_last20 -----------------------------------"
time ${TOOLDIR}/mkGNUplot_last20 40
# NB: Now takes a param instead of using fixed 20 latest data sets.

# Create plots per platform for ~last month
echo "-- doplot _last20 -------------------------------------"
time ${TOOLDIR}/doplot _last20

# Create summary plots over all platforms for ~last month
# time ${TOOLDIR}/doplot_all_lastMonth
echo "-- doplot_all _last20 ---------------------------------"
time ${TOOLDIR}/doplot_all _last20

echo "***** ${DERBYDIR} *********"
