#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REVISION=$1
DETAILS=$2

if [ "${DERBYDIR}" == "" ]
then
  echo "DERBYDIR is undefined!"
  exit
fi
if [ ! -e ${DERBYDIR} ]
then
  echo "${DERBYDIR} does not exist!"
  exit
fi

SUMMARY=${DERBYDIR}/summary.txt
if [ "${DETAILS}" == "details" ]
then
  SUMMARY=${DERBYDIR}/summary-full.txt
fi

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

echo -n " ${REVISION}: " > ${SUMMARY}

# DEBUG echo "demo: " >> ${SUMMARY}
# DEBUG ${TOOLDIR}/platformsFailCount ${REVISION} "${DETAILS}" demo >> ${SUMMARY}
# DEBUG ## echo "/" >> ${SUMMARY}
# DEBUG ## ${TOOLDIR}/platformsDurPrcnt ${REVISION} "${DETAILS}" demo >> ${SUMMARY}

echo "derbyall: " >> ${SUMMARY}
${TOOLDIR}/platformsFailCount ${REVISION} "${DETAILS}" derbyall >> ${SUMMARY}
## echo "/" >> ${SUMMARY}
## ${TOOLDIR}/platformsDurPrcnt ${REVISION} "${DETAILS}" derbyall >> ${SUMMARY}

echo ", suites.All: " >> ${SUMMARY}
${TOOLDIR}/platformsFailCount ${REVISION} "${DETAILS}" org.apache.derbyTesting.functionTests.suites.All >> ${SUMMARY}
## echo "/" >> ${SUMMARY}
## ${TOOLDIR}/platformsDurPrcnt ${REVISION} "${DETAILS}" org.apache.derbyTesting.functionTests.suites.All >> ${SUMMARY}

chmod go+r ${SUMMARY}

