#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REVISION=$1
SHOWDETAILS=$2
SUITE=$3

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

# Get the set of platforms
cd ${TESTLOGDIR}
PLATFORMS=`ls`

DERBALLFAILS="["
for PLATFORM in ${PLATFORMS} # TinderBox uses ONE platform..
do
  # DEBUG echo -n "${PLATFORM} "; pwd
  if [ -e ${PLATFORM}/externallyVisible ] || [ "${SHOWDETAILS}" = "details" ]
  then
    if [ -e ${PLATFORM}/${REVISION}.csv ]
    then
      #  2: Number, 3: OK, 4: Failed, 5: Skipped, 6: time
      ## RES=`grep "^derbyall " ${PLATFORM}/${REVISION}.csv`
      RES=`grep "^${SUITE} " ${PLATFORM}/${REVISION}.csv`
      FAILED=`echo ${RES} | gawk '{ print $4 }'`
      if [ "${FAILED}" == "" ]
      then
        FAILED="?"
      fi
      DERBALLFAILS="${DERBALLFAILS} ${FAILED} "
    else
      DERBALLFAILS="${DERBALLFAILS} - "
    fi
  fi # visible, showdetails
done # PLATFORMS
DERBALLFAILS="${DERBALLFAILS}]"

echo ${DERBALLFAILS}
