#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MODEL=`uname -m` # Minimalistic

# Following gives details
psrinfo -v > psrinfo$$
NUMBER=`psrinfo -p`
PROC=`grep "processor operates at " psrinfo$$ | head -1 | gawk  '{ print $2 }'`
FREQ=`grep "processor operates at " psrinfo$$ | head -1 | gawk  '{ print $6 }'`
CACHE='unknown'
ARCH=`psrinfo -vp 1 | tail -1 | sed -e 's/  //g'`
MODEL="${MODEL} ${PROC} (${ARCH})"

# echo "Installed memory:"
MEMTOTAL=`prtconf | grep "Memory size" | gawk -F: '{ print $2 }' | sed -e 's/  //g'`
MEMFREE='unknown'

rm psrinfo$$

echo "${NUMBER} X ${MODEL}: ${FREQ} MHz, ${CACHE} cache. ${MEMTOTAL} Total Memory."
