#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# export DERBYDIR="${HOME}/Apache/Derby"
DERBYDIR=$1

if [ "${DERBYDIR}" = "" ]
then
  echo "DERBYDIR must be defined."
  exit
fi
if [ ! -e ${DERBYDIR} ]
then
  echo "Nonexisting DERBYDIR: ${DERBYDIR} was given to $0."
  exit
fi

cd ${DERBYDIR}

HOST=`uname -n`

. ./env.sh
. ./testenv.sh

TOOLDIR="${DERBYDIR}/${BRANCH_DIR}/tools/testing/reporting/scripts"
. ${TOOLDIR}/env

SANDBOX=`basename ${DERBYDIR}`
if [ ! -e ${BUILDLOGDIR}/buildOK ]
then
  echo "Derby was NOT updated or build failed"
  echo "  ${BUILDLOGDIR}/buildOK does not exist."
  ### UNCOMMENT TO SEND MAIL. ${TOOLDIR}/textMail "${SANDBOX} was NOT updated or build failed" "${MAILTOINT}" "${BUILDLOGDIR}/lastBuildInfo"
  exit
fi

mkdir -p TestRunLogs
cd TestRunLogs

echo "${TOOLDIR}/runAllTests ../testing/testlist ${DERBYDIR}/testing/testlog > ${HOST}.log" > ${HOST}.log
${TOOLDIR}/runAllTests ../testing/testlist ${DERBYDIR}/testing/testlog >> ${HOST}.log 2>${HOST}.err &

