#!/bin/bash
if [ "$1" == "" ]
then
  echo "Missing Subject"
  exit
fi
if [ "$2" == "" ]
then
  echo "Missing toMailAdr"
  exit
fi
if [ "$3" == "" ]
then
  echo "Missing File(s)"
  echo "NB! Must be plain text files with nothing that the shell might try to interpret!"
  exit
fi
SUBJECT=$1
TO=$2
FILELIST=$3

# echo "Creating sendmail file"

echo "Subject: ${SUBJECT}" >>  sendmailfile$$
echo "To: ${TO}" >>  sendmailfile$$
echo "From: John.Doe@ACME.COM" >>  sendmailfile$$

for FILE in ${FILELIST}
do

  # echo "File: ${FILE}:" >>  sendmailfile$$
  # echo "" >>  sendmailfile$$

  cat ${FILE} >> sendmailfile$$

  # echo "-------" >>  sendmailfile$$
  echo "" >>  sendmailfile$$

done

cat sendmailfile$$

echo "Sending mail w/Subject '"${SUBJECT}"' to ${TO}"
/usr/lib/sendmail -t < sendmailfile$$


rm sendmailfile$$
