#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$1" == "" ]
then
  echo "Missing Subject"
  exit
fi
if [ "$2" == "" ]
then
  echo "Missing toMailAdr"
  exit
fi
if [ "$3" == "" ]
then
  echo "Missing File(s)"
  echo "NB! Must be plain text files with nothing that the shell might try to interpret!"
  exit
fi
SUBJECT=$1
TO=$2
FILELIST=$3

# echo "Creating sendmail file"

echo "Subject: ${SUBJECT}" >>  sendmailfile$$
echo "To: ${TO}" >>  sendmailfile$$
echo "From: John.Doe@ACME.COM" >>  sendmailfile$$

for FILE in ${FILELIST}
do

  # echo "File: ${FILE}:" >>  sendmailfile$$
  # echo "" >>  sendmailfile$$

  cat ${FILE} >> sendmailfile$$

  # echo "-------" >>  sendmailfile$$
  echo "" >>  sendmailfile$$

done

cat sendmailfile$$

echo "Sending mail w/Subject '"${SUBJECT}"' to ${TO}"
/usr/lib/sendmail -t < sendmailfile$$


rm sendmailfile$$
