/*

   Licensed Materials - Property of IBM
   Cloudscape - Package org.apache.derby.iapi.store.raw
   (C) Copyright IBM Corp. 1997, 2004. All Rights Reserved.
   US Government Users Restricted Rights - Use, duplication or
   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

 */

package org.apache.derby.iapi.store.raw;

/**
	A Compensation operation can compensate for the action of a log operation.
	A Compensation operation itself is not undo-able, i.e., it is loggable but
	not undoable.

	A Compensation operation is generated by the logging system when it calls
	undoable.generateUndo().  GenerateUndo should be the <B>only</B> way a 
	compensation operation can be made.

	@see Undoable#generateUndo
*/
public interface Compensation extends Loggable {
	/**
		IBM Copyright &copy notice.
	*/
	public static final String copyrightNotice = org.apache.derby.iapi.reference.Copyright.SHORT_1997_2004;

	/**
	  Set up the undoable operation during recovery redo.

	  @param op the Undoable operation
	  @see Loggable#needsRedo
	*/
	public void setUndoOp(Undoable op);
}
