/*

   Derby - Class org.apache.derby.jdbc.ClientXADataSource

   Copyright (c) 2001, 2005 The Apache Software Foundation or its licensors, where applicable.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

package org.apache.derby.jdbc;

import javax.sql.*;
import org.apache.derby.client.ClientXAConnection;


public class ClientXADataSource extends ClientDataSource implements XADataSource,
                                                                  java.io.Serializable,
                                                                  javax.naming.Referenceable
{
  public static final String className__ = "org.apache.derby.jdbc.ClientXADataSource";

  // following serialVersionUID was generated by the JDK's serialver program
  // verify it everytime that ClientXADataSource is modified
  static final long serialVersionUID = 7057075094707674880L;

  private String password = null;
  synchronized public void setPassword (String password) { this.password = password; }
  public final static String propertyKey_password = "password";

  public ClientXADataSource()
  {
    this.setResultSetHoldability( org.apache.derby.client.ClientBaseDataSource.CLOSE_CURSORS_AT_COMMIT );
  }

  public XAConnection getXAConnection() throws java.sql.SQLException
  {

    return getXAConnection(this.user, this.password);
  }

  public XAConnection getXAConnection (String user, String password) throws java.sql.SQLException
  {
    org.apache.derby.client.am.LogWriter dncLogWriter = super.computeDncLogWriterForNewConnection ("_xads");


    ClientXAConnection xaConn_ = new ClientXAConnection( this,
          (org.apache.derby.client.net.NetLogWriter) dncLogWriter,
          user,
          password);
    return xaConn_;
  }
}
